[project]
name = "twitter-scraper"
version = "0.1.0"
description = "Twitter scraper using snscrape"
requires-python = ">=3.8"
dependencies = [
    "snscrape",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
